<?php
/**
 * AccountsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  StreamNetworkApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Live4.tv - Stream Targets
 *
 * Omnichannel for live streaming on social networks  We're glad that you chose to use Live4.tv's API for managing your connection with social networks.   Here in this documentation, you will find a step-by-step for integrating our API.  Feel free to contact us in case you need any help.  The login flow:  ![login flow image](https://api-stream-network.live4.tv/mermaid-diagram-login-flow.png \"Login flow image\")
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contato@live4.tv
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace StreamNetworkApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use StreamNetworkApi\ApiException;
use StreamNetworkApi\Configuration;
use StreamNetworkApi\HeaderSelector;
use StreamNetworkApi\ObjectSerializer;

/**
 * AccountsApi Class Doc Comment
 *
 * @category Class
 * @package  StreamNetworkApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AccountsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'socialNetworkAccountControllerGetAccount' => [
            'application/json',
        ],
        'socialNetworkAccountControllerGetAuthoriseUrl' => [
            'application/json',
        ],
    ];

    /**
         * @param ClientInterface $client
         * @param Configuration   $config
         * @param HeaderSelector  $selector
         * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
         */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation socialNetworkAccountControllerGetAccount
     *
     * Get social account information logged from user account
     *
     * @param  string $x_api_key x_api_key (required)
     * @param  string $user_external_id The user&#39;s unique identifier on your system. The same of you use to authorise-url endpoint. (required)
     * @param  string $uuid The reference to the new account that you can use to identify the account. The same of you use to authorise-url endpoint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['socialNetworkAccountControllerGetAccount'] to see the possible values for this operation
     *
     * @throws \StreamNetworkApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \StreamNetworkApi\Model\SocialNetworkAccount|\StreamNetworkApi\Model\HttpExceptionResponse
     */
    public function socialNetworkAccountControllerGetAccount($x_api_key, $user_external_id, $uuid, string $contentType = self::contentTypes['socialNetworkAccountControllerGetAccount'][0])
    {
        list($response) = $this->socialNetworkAccountControllerGetAccountWithHttpInfo($x_api_key, $user_external_id, $uuid, $contentType);
        return $response;
    }

    /**
     * Operation socialNetworkAccountControllerGetAccountWithHttpInfo
     *
     * Get social account information logged from user account
     *
     * @param  string $x_api_key (required)
     * @param  string $user_external_id The user&#39;s unique identifier on your system. The same of you use to authorise-url endpoint. (required)
     * @param  string $uuid The reference to the new account that you can use to identify the account. The same of you use to authorise-url endpoint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['socialNetworkAccountControllerGetAccount'] to see the possible values for this operation
     *
     * @throws \StreamNetworkApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \StreamNetworkApi\Model\SocialNetworkAccount|\StreamNetworkApi\Model\HttpExceptionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function socialNetworkAccountControllerGetAccountWithHttpInfo($x_api_key, $user_external_id, $uuid, string $contentType = self::contentTypes['socialNetworkAccountControllerGetAccount'][0])
    {
        $request = $this->socialNetworkAccountControllerGetAccountRequest($x_api_key, $user_external_id, $uuid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\StreamNetworkApi\Model\SocialNetworkAccount' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\StreamNetworkApi\Model\SocialNetworkAccount' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\StreamNetworkApi\Model\SocialNetworkAccount', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\StreamNetworkApi\Model\HttpExceptionResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\StreamNetworkApi\Model\HttpExceptionResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\StreamNetworkApi\Model\HttpExceptionResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\StreamNetworkApi\Model\SocialNetworkAccount';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\StreamNetworkApi\Model\SocialNetworkAccount',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\StreamNetworkApi\Model\HttpExceptionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation socialNetworkAccountControllerGetAccountAsync
     *
     * Get social account information logged from user account
     *
     * @param  string $x_api_key (required)
     * @param  string $user_external_id The user&#39;s unique identifier on your system. The same of you use to authorise-url endpoint. (required)
     * @param  string $uuid The reference to the new account that you can use to identify the account. The same of you use to authorise-url endpoint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['socialNetworkAccountControllerGetAccount'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function socialNetworkAccountControllerGetAccountAsync($x_api_key, $user_external_id, $uuid, string $contentType = self::contentTypes['socialNetworkAccountControllerGetAccount'][0])
    {
        return $this->socialNetworkAccountControllerGetAccountAsyncWithHttpInfo($x_api_key, $user_external_id, $uuid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation socialNetworkAccountControllerGetAccountAsyncWithHttpInfo
     *
     * Get social account information logged from user account
     *
     * @param  string $x_api_key (required)
     * @param  string $user_external_id The user&#39;s unique identifier on your system. The same of you use to authorise-url endpoint. (required)
     * @param  string $uuid The reference to the new account that you can use to identify the account. The same of you use to authorise-url endpoint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['socialNetworkAccountControllerGetAccount'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function socialNetworkAccountControllerGetAccountAsyncWithHttpInfo($x_api_key, $user_external_id, $uuid, string $contentType = self::contentTypes['socialNetworkAccountControllerGetAccount'][0])
    {
        $returnType = '\StreamNetworkApi\Model\SocialNetworkAccount';
        $request = $this->socialNetworkAccountControllerGetAccountRequest($x_api_key, $user_external_id, $uuid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'socialNetworkAccountControllerGetAccount'
     *
     * @param  string $x_api_key (required)
     * @param  string $user_external_id The user&#39;s unique identifier on your system. The same of you use to authorise-url endpoint. (required)
     * @param  string $uuid The reference to the new account that you can use to identify the account. The same of you use to authorise-url endpoint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['socialNetworkAccountControllerGetAccount'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function socialNetworkAccountControllerGetAccountRequest($x_api_key, $user_external_id, $uuid, string $contentType = self::contentTypes['socialNetworkAccountControllerGetAccount'][0])
    {

        // verify the required parameter 'x_api_key' is set
        if ($x_api_key === null || (is_array($x_api_key) && count($x_api_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_api_key when calling socialNetworkAccountControllerGetAccount'
            );
        }

        // verify the required parameter 'user_external_id' is set
        if ($user_external_id === null || (is_array($user_external_id) && count($user_external_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $user_external_id when calling socialNetworkAccountControllerGetAccount'
            );
        }

        // verify the required parameter 'uuid' is set
        if ($uuid === null || (is_array($uuid) && count($uuid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $uuid when calling socialNetworkAccountControllerGetAccount'
            );
        }


        $resourcePath = '/api/v1/social-network-account/{userExternalId}/{uuid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_api_key !== null) {
            $headerParams['x-api-key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }

        // path params
        if ($user_external_id !== null) {
            $resourcePath = str_replace(
                '{' . 'userExternalId' . '}',
                ObjectSerializer::toPathValue($user_external_id),
                $resourcePath
            );
        }
        // path params
        if ($uuid !== null) {
            $resourcePath = str_replace(
                '{' . 'uuid' . '}',
                ObjectSerializer::toPathValue($uuid),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation socialNetworkAccountControllerGetAuthoriseUrl
     *
     * Add a new social network account (e.g instagram account)
     *
     * @param  string $x_api_key x_api_key (required)
     * @param  string $network The social network code (required)
     * @param  \StreamNetworkApi\Model\GetAuthoriseUrlRequest $get_authorise_url_request get_authorise_url_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['socialNetworkAccountControllerGetAuthoriseUrl'] to see the possible values for this operation
     *
     * @throws \StreamNetworkApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \StreamNetworkApi\Model\Redirect|\StreamNetworkApi\Model\HttpExceptionResponse
     */
    public function socialNetworkAccountControllerGetAuthoriseUrl($x_api_key, $network, $get_authorise_url_request, string $contentType = self::contentTypes['socialNetworkAccountControllerGetAuthoriseUrl'][0])
    {
        list($response) = $this->socialNetworkAccountControllerGetAuthoriseUrlWithHttpInfo($x_api_key, $network, $get_authorise_url_request, $contentType);
        return $response;
    }

    /**
     * Operation socialNetworkAccountControllerGetAuthoriseUrlWithHttpInfo
     *
     * Add a new social network account (e.g instagram account)
     *
     * @param  string $x_api_key (required)
     * @param  string $network The social network code (required)
     * @param  \StreamNetworkApi\Model\GetAuthoriseUrlRequest $get_authorise_url_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['socialNetworkAccountControllerGetAuthoriseUrl'] to see the possible values for this operation
     *
     * @throws \StreamNetworkApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \StreamNetworkApi\Model\Redirect|\StreamNetworkApi\Model\HttpExceptionResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function socialNetworkAccountControllerGetAuthoriseUrlWithHttpInfo($x_api_key, $network, $get_authorise_url_request, string $contentType = self::contentTypes['socialNetworkAccountControllerGetAuthoriseUrl'][0])
    {
        $request = $this->socialNetworkAccountControllerGetAuthoriseUrlRequest($x_api_key, $network, $get_authorise_url_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\StreamNetworkApi\Model\Redirect' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\StreamNetworkApi\Model\Redirect' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\StreamNetworkApi\Model\Redirect', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\StreamNetworkApi\Model\HttpExceptionResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\StreamNetworkApi\Model\HttpExceptionResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\StreamNetworkApi\Model\HttpExceptionResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\StreamNetworkApi\Model\Redirect';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\StreamNetworkApi\Model\Redirect',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\StreamNetworkApi\Model\HttpExceptionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation socialNetworkAccountControllerGetAuthoriseUrlAsync
     *
     * Add a new social network account (e.g instagram account)
     *
     * @param  string $x_api_key (required)
     * @param  string $network The social network code (required)
     * @param  \StreamNetworkApi\Model\GetAuthoriseUrlRequest $get_authorise_url_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['socialNetworkAccountControllerGetAuthoriseUrl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function socialNetworkAccountControllerGetAuthoriseUrlAsync($x_api_key, $network, $get_authorise_url_request, string $contentType = self::contentTypes['socialNetworkAccountControllerGetAuthoriseUrl'][0])
    {
        return $this->socialNetworkAccountControllerGetAuthoriseUrlAsyncWithHttpInfo($x_api_key, $network, $get_authorise_url_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation socialNetworkAccountControllerGetAuthoriseUrlAsyncWithHttpInfo
     *
     * Add a new social network account (e.g instagram account)
     *
     * @param  string $x_api_key (required)
     * @param  string $network The social network code (required)
     * @param  \StreamNetworkApi\Model\GetAuthoriseUrlRequest $get_authorise_url_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['socialNetworkAccountControllerGetAuthoriseUrl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function socialNetworkAccountControllerGetAuthoriseUrlAsyncWithHttpInfo($x_api_key, $network, $get_authorise_url_request, string $contentType = self::contentTypes['socialNetworkAccountControllerGetAuthoriseUrl'][0])
    {
        $returnType = '\StreamNetworkApi\Model\Redirect';
        $request = $this->socialNetworkAccountControllerGetAuthoriseUrlRequest($x_api_key, $network, $get_authorise_url_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'socialNetworkAccountControllerGetAuthoriseUrl'
     *
     * @param  string $x_api_key (required)
     * @param  string $network The social network code (required)
     * @param  \StreamNetworkApi\Model\GetAuthoriseUrlRequest $get_authorise_url_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['socialNetworkAccountControllerGetAuthoriseUrl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function socialNetworkAccountControllerGetAuthoriseUrlRequest($x_api_key, $network, $get_authorise_url_request, string $contentType = self::contentTypes['socialNetworkAccountControllerGetAuthoriseUrl'][0])
    {

        // verify the required parameter 'x_api_key' is set
        if ($x_api_key === null || (is_array($x_api_key) && count($x_api_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_api_key when calling socialNetworkAccountControllerGetAuthoriseUrl'
            );
        }

        // verify the required parameter 'network' is set
        if ($network === null || (is_array($network) && count($network) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $network when calling socialNetworkAccountControllerGetAuthoriseUrl'
            );
        }

        // verify the required parameter 'get_authorise_url_request' is set
        if ($get_authorise_url_request === null || (is_array($get_authorise_url_request) && count($get_authorise_url_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $get_authorise_url_request when calling socialNetworkAccountControllerGetAuthoriseUrl'
            );
        }


        $resourcePath = '/api/v1/social-network-account/{network}/authorise-url';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_api_key !== null) {
            $headerParams['x-api-key'] = ObjectSerializer::toHeaderValue($x_api_key);
        }

        // path params
        if ($network !== null) {
            $resourcePath = str_replace(
                '{' . 'network' . '}',
                ObjectSerializer::toPathValue($network),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($get_authorise_url_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($get_authorise_url_request));
            } else {
                $httpBody = $get_authorise_url_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
