<?php
/**
 * SocialNetworksApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  StreamNetworkApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Live4.tv - Stream Targets
 *
 * Omnichannel for live streaming on social networks  We're glad that you chose to use Live4.tv's API for managing your connection with social networks.   Here in this documentation, you will find a step-by-step for integrating our API.  Feel free to contact us in case you need any help.  The login flow:  ![login flow image](https://api-stream-network.live4.tv/mermaid-diagram-login-flow.png \"Login flow image\")
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contato@live4.tv
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace StreamNetworkApi\Test\Api;

use \StreamNetworkApi\Configuration;
use \StreamNetworkApi\ApiException;
use \StreamNetworkApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SocialNetworksApiTest Class Doc Comment
 *
 * @category Class
 * @package  StreamNetworkApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SocialNetworksApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for socialNetworkControllerGetAllActive
     *
     * Get all social network integrations available.
     *
     */
    public function testSocialNetworkControllerGetAllActive()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
